/**
 * DOM helpers for Maplog. Markup is always generated by the Maplog SVG module
 * from catalogue ids and numbers, never from typed text, and is parsed as SVG.
 */

/** An SVG element from generated markup, owned by the given document. */
export function svgElement(doc: Document, markup: string): Element {
    const parsed = new DOMParser().parseFromString(markup, 'image/svg+xml');
    return doc.importNode(parsed.documentElement, true);
}
