/*
 * Lorelog notation: typed model.
 *
 * Lorelog by Roberto Bisceglie (Loreseed Workshop), a sibling of Lonelog.
 * Licensed under CC BY-SA 4.0: https://creativecommons.org/licenses/by-sa/4.0/
 *
 * Pure TypeScript: no Obsidian or DOM imports.
 */
import type { Tag } from '../../campaign/partylog';

/** Tag types defined by the spec (section 5.2). Custom types keep their written head. */
export const LORELOG_TAG_TYPES = ['F', 'N', 'L', 'Rule', 'Tension', 'Hist', 'Term', 'Q', 'Need'] as const;
export type LorelogTagType = (typeof LORELOG_TAG_TYPES)[number];

/** Tension states (section 5.3). */
export const TENSION_STATES = ['latent', 'open', 'seasonal', 'cyclic', 'resolved'] as const;
/** Question and need states (section 5.3). */
export const BACKLOG_STATES = ['open', 'answered', 'dropped'] as const;

export type LorelogNoteType = 'why' | 'note' | 'parked';

/** `?` or `!` trigger. `unit` is the story unit of a need (`Ch3` in `! Ch3 needs ...`). */
export interface LorelogTrigger {
	kind: 'question' | 'need';
	text: string;
	unit?: string;
	/** Section reference, e.g. `Politics` from `(§Politics)`. */
	section?: string;
	author?: string;
	line: number;
}

/** `=` (fact), `=?` (provisional) or `x=` (retraction). */
export interface LorelogFact {
	kind: 'fact' | 'provisional' | 'retraction';
	text: string;
	tags: Tag[];
	author?: string;
	line: number;
	/** Set on a fact that a later `x=` line retracted. */
	retracted: boolean;
	retractedBy?: number;
	/** Set on a provisional fact that a later `=` line confirmed. */
	confirmedBy?: number;
	/** Reason from a `(why: ...)` note that follows a retraction. */
	reason?: string;
}

/** `~` friction. */
export interface LorelogFriction {
	text: string;
	tags: Tag[];
	author?: string;
	line: number;
}

/** `>> ...` ripple. `section` is set for `>> §Section: text`. */
export interface LorelogRipple {
	text: string;
	tags: Tag[];
	section?: string;
	line: number;
}

/** `t: Name [subject] -> Result` with optional indented detail lines. */
export interface LorelogTest {
	name: string;
	subject?: string;
	result?: string;
	status: 'pass' | 'gap' | 'fail' | 'other' | 'none';
	details: string[];
	line: number;
}

/** `tbl:` or `gen:` lookup, with optional indented table lines. */
export interface LorelogTable {
	source: 'tbl' | 'gen';
	expression: string;
	details: string[];
	line: number;
}

export interface LorelogNote {
	type: LorelogNoteType;
	text: string;
	line: number;
}

/** A line made only of tags, e.g. the backlog snapshot `[Q:Warden oversight|open|p1]`. */
export interface LorelogTagLine {
	tags: Tag[];
	line: number;
}

export interface LorelogCycle {
	/** `C7`, `C7.1`, `C7a`, `M1-C4`. Undefined for notation outside any cycle heading. */
	id?: string;
	title?: string;
	/** Section reference from the heading, e.g. `Politics` from `(§Politics)`. */
	section?: string;
	/** True for a branch marked `(kept)`. */
	kept?: boolean;
	line: number;
	/** Build number the cycle belongs to, if any. */
	build?: number;
	/** Phase name in effect when the cycle starts, if any. */
	phase?: string;
	triggers: LorelogTrigger[];
	vias: string[];
	facts: LorelogFact[];
	frictions: LorelogFriction[];
	ripples: LorelogRipple[];
	/** `?` and `!` lines written after a ripple, generated by this cycle. */
	followUps: LorelogTrigger[];
	tests: LorelogTest[];
	tables: LorelogTable[];
	notes: LorelogNote[];
	tags: LorelogTagLine[];
}

export interface LorelogBuildMeta {
	date?: string;
	duration?: string;
	phase?: string;
	cycles?: string;
	focus?: string;
}

export interface LorelogBuild {
	number: number;
	line: number;
	meta: LorelogBuildMeta;
	/** Fields from the analog `[Key] value` form, or other meta keys, in source order. */
	fields: Record<string, string>;
}

export interface LorelogPhase {
	number?: number;
	name: string;
	line: number;
}

export interface LorelogWorldHeader {
	title?: string;
	/** Other front-matter or analog fields, in source order. Keys are lower-cased. */
	fields: Record<string, string>;
	line?: number;
}

export interface LorelogLog {
	header: LorelogWorldHeader;
	builds: LorelogBuild[];
	phases: LorelogPhase[];
	cycles: LorelogCycle[];
}

/** One line of notation after classification. Used by `parseLorelogLine`. */
export type LorelogLine =
	| { kind: 'blank' }
	| { kind: 'prose'; text: string }
	| { kind: 'cycle-heading'; id: string; title?: string; section?: string; kept?: boolean }
	| { kind: 'inline-cycle'; id: string; parts: LorelogLine[] }
	| { kind: 'build-heading'; number: number; meta: LorelogBuildMeta; fields: Record<string, string> }
	| { kind: 'phase'; number?: number; name: string }
	| { kind: 'world-heading'; title: string }
	| { kind: 'trigger'; trigger: LorelogTrigger }
	| { kind: 'fact'; fact: Omit<LorelogFact, 'retracted' | 'line'> }
	| { kind: 'friction'; friction: Omit<LorelogFriction, 'line'> }
	| { kind: 'ripple'; ripple: Omit<LorelogRipple, 'line'> }
	| { kind: 'via'; method: string }
	| { kind: 'test'; name: string; subject?: string; result?: string }
	| { kind: 'test-result'; result: string }
	| { kind: 'table'; source: 'tbl' | 'gen'; expression: string }
	| { kind: 'note'; type: LorelogNoteType; text: string }
	| { kind: 'tags'; tags: Tag[] }
	| { kind: 'header-field'; key: string; value: string }
	| { kind: 'header-meta'; pairs: Array<[string, string]> };
